title: Daniel Saavedra
logo: /assets/img/Websitepic.jpg
description: |
  Aspiring Data Analyst/Scientist | Computer Science Graduate  
  [LinkedIn](https://www.linkedin.com/in/daniel--saavedra) | 
  [GitHub](https://github.com/Dansaa27) | 
  [Tableau](https://public.tableau.com/app/profile/daniel.saavedra4145/vizzes)
show_downloads: true
theme: jekyll-theme-minimal
